---

- hosts: all
  remote_user: root

  tasks: 

    - name: Upgrade Debian
      apt: 
        update_cache: yes
        upgrade: "yes"

    - name: Install extra
      apt:
        name: 
          - curl
          - aptitude
          - sudo
        state: present

    - name: Create yb user 
      user:
        name: yb
        group: users
        shell: /bin/bash
        state: present

    - name: Download YugabyteDB Archive
      unarchive:
        src: https://downloads.yugabyte.com/yugabyte-2.1.5.0-linux.tar.gz
        dest: /home/yb
        remote_src: yes
      become_user: yb
      become: yes

    - name: Create bin symbolic link
      file:
        src: /home/yb/yugabyte-2.1.5.0/bin
        dest: /home/yb/bin
        state: link
      become_user: yb
      become: yes

    - name: Add bin to path
      lineinfile:
        path: /home/yb/.bashrc
        line: "export PATH=~/bin:$PATH"
        insertafter: EOF
      become_user: yb
      become: yes

    - name: Run YugabyteDB Install
      shell: bin/post_install.sh
      args:
        chdir: /home/yb/yugabyte-2.1.5.0
        creates: /home/yb/yugabyte-2.1.5.0/.post_install.sh.completed
      become_user: yb
      become: yes

    - name: Create YugabyteDB Cluster
      shell: bin/yb-ctl create --listen_ip 0.0.0.0
      args:
        chdir: /home/yb/yugabyte-2.1.5.0
        creates: /home/yb/yugabyte-data
      become_user: yb
      become: yes
      

# vim: ts=2 et nowrap autoindent