---

- hosts: all
  remote_user: root

  vars: 
    yugabyte_version: 2.11.2.0-b89
    yugabyte_download: https://downloads.yugabyte.com/yugabyte-{{yugabyte_version}}-linux.tar.gz
    db_array: []
    master_address_array: []

  tasks: 

    - name: Create list of db server names
      set_fact: 
        db_array: '{{ db_array + [ "subutai." + environment_name + "." + item ] }}'
      with_items: '{{ groups["servers"] }}'
      when: 'inventory_hostname == groups["servers"][0]'

    - name: Create array of master_addresses
      set_fact: 
        master_address_array: '{{ master_address_array + [ hostvars[item].ansible_default_ipv4.address + ":7100" ] }}'
      with_items: '{{ groups["servers"] }}'
      when: 'inventory_hostname == groups["servers"][0]'

    - name: Create db_list
      set_fact:
        db_list: '{{ db_array | join(",") }}'
      when: 'inventory_hostname == groups["servers"][0]'

    - name: create master_addresses
      set_fact: 
        master_addresses: '{{ master_address_array | join(",") }}'
      when: 'inventory_hostname == groups["servers"][0]'

    - name: Upgrade Debian
      apt: 
        update_cache: yes
        upgrade: "yes"

    - name: Install extra
      apt:
        name: 
          - curl
          - aptitude
          - sudo
          - telnet
        state: present

    - name: Create yb-master service
      template:
        src: files/yb-master.service
        dest: /lib/systemd/system/yb-master.service
  
    - name: Make sure yb-master is stopped
      systemd:
        name: yb-master
        enabled: no
        daemon_reload: yes
        state: stopped

    - name: Create yb-tserver service
      template:
        src: files/yb-tserver.service
        dest: /lib/systemd/system/yb-tserver.service
    
    - name: Make sure yb-tserver is stopped
      systemd:
        name: yb-tserver
        enabled: no
        daemon_reload: yes
        state: stopped

    - name: Create yb user 
      user:
        name: yb
        group: users
        shell: /bin/bash
        state: present

    - name: Download YugabyteDB Archive
      unarchive:
        src: "{{ yugabyte_download}}"
        dest: /home/yb
        remote_src: yes
      become_user: yb
      become: yes

    - name: Create bin symbolic link
      file:
        src: /home/yb/yugabyte-{{ yugabyte_version }}/bin
        dest: /home/yb/bin
        state: link
      become_user: yb
      become: yes

    - name: Add bin to path
      lineinfile:
        path: /home/yb/.bashrc
        line: "export PATH=~/bin:$PATH"
        insertafter: EOF
      become_user: yb
      become: yes

    - name: Nuke old install file
      file: 
        name: /home/yb/yugabyte-{{ yugabyte_version }}/.post_install.sh.completed
        state: absent

    - name: Run YugabyteDB Install
      shell: yugabyte-{{yugabyte_version}}/bin/post_install.sh
      args:
        chdir: /home/yb
        creates: /home/yb/yugabyte-{{yugabyte_version}}/.post_install.sh.completed
      become_user: yb
      become: yes

    - name: Nuke directory (temporary)
      file:
        path: /home/yb/data
        owner: yb
        group: users
        state: absent
    
    - name: Create data directory
      file:
        path: /home/yb/data
        owner: yb
        group: users
        state: directory

    - name: Create master config
      template: 
        src: files/master.conf
        dest: /home/yb/master.conf
      become_user: yb
      become: yes

    - name: Restart yb-master
      systemd:
        name: yb-master
        enabled: yes
        state: restarted

    - name: Create tserver config
      template: 
        src: files/tserver.conf
        dest: /home/yb/tserver.conf
      become_user: yb
      become: yes
  
    - name: Restart yb-tserver
      systemd:
        name: yb-tserver
        enabled: yes
        state: restarted

    - name: Create master_addresses
      template:
        src: files/master_addresses
        dest: /home/yb/master_addresses
        owner: yb
        group: users

    - name: Wait a bit for servers to start
      pause:
        seconds: 30

    - name: Modify placement
      shell: 'yugabyte-{{yugabyte_version}}/bin/yb-admin --master_addresses={{ master_addresses }} modify_placement_info {{ db_list }} 3'
      args:
        chdir: /home/yb
      become_user: yb
      become: yes
      when: 'inventory_hostname == groups["servers"][0]'
      
    - name: Create .pgpass
      template:
        src: files/pgpass
        dest: /home/yb/.pgpass
        owner: yb
        group: users
        mode: "0600"

# vim: ts=2 et nowrap autoindent
