---

- hosts: all
  remote_user: root

  tasks: 

    - name: Upgrade Debian
      apt: 
        update_cache: yes
        upgrade: "yes"

    - name: Install extra
      apt:
        name: 
          - curl
          - aptitude
          - sudo
          - telnet
        state: present

    - name: Create yb-master service
      template:
        src: files/yb-master.service
        dest: /lib/systemd/system/yb-master.service
  
    - name: Make sure yb-master is stopped
      systemd:
        name: yb-master
        enabled: no
        daemon_reload: yes
        state: stopped

    - name: Create yb-tserver service
      template:
        src: files/yb-tserver.service
        dest: /lib/systemd/system/yb-tserver.service
    
    - name: Make sure yb-tserver is stopped
      systemd:
        name: yb-tserver
        enabled: no
        daemon_reload: yes
        state: stopped

    - name: Create yb user 
      user:
        name: yb
        group: users
        shell: /bin/bash
        state: present

    - name: Download YugabyteDB Archive
      unarchive:
        src: https://downloads.yugabyte.com/yugabyte-2.1.5.0-linux.tar.gz
        dest: /home/yb
        remote_src: yes
      become_user: yb
      become: yes

    - name: Create bin symbolic link
      file:
        src: /home/yb/yugabyte-2.1.5.0/bin
        dest: /home/yb/bin
        state: link
      become_user: yb
      become: yes

    - name: Add bin to path
      lineinfile:
        path: /home/yb/.bashrc
        line: "export PATH=~/bin:$PATH"
        insertafter: EOF
      become_user: yb
      become: yes

    - name: Nuke old install file
      file: 
        name: /home/yb/yugabyte-2.1.5.0/.post_install.sh.completed
        state: absent

    - name: Run YugabyteDB Install
      shell: yugabyte-2.1.5.0/bin/post_install.sh
      args:
        chdir: /home/yb
        creates: /home/yb/yugabyte-2.1.5.0/.post_install.sh.completed
      become_user: yb
      become: yes

    - name: Nuke directory (temporary)
      file:
        path: /home/yb/data
        owner: yb
        group: users
        state: absent
    
    - name: Create data directory
      file:
        path: /home/yb/data
        owner: yb
        group: users
        state: directory

    - name: Create master config
      template: 
        src: files/master.conf
        dest: /home/yb/master.conf
      become_user: yb
      become: yes

    - name: Restart yb-master
      systemd:
        name: yb-master
        enabled: yes
        state: restarted

    - name: Create tserver config
      template: 
        src: files/tserver.conf
        dest: /home/yb/tserver.conf
      become_user: yb
      become: yes
  
    - name: Restart yb-tserver
      systemd:
        name: yb-tserver
        enabled: yes
        state: restarted

#    - name: Create YugabyteDB Cluster
#      shell: bin/yb-ctl create --listen_ip 0.0.0.0 --timeout-processes-running-sec 60
#      args:
#        chdir: /home/yb/yugabyte-2.1.5.0
#        creates: /home/yb/yugabyte-data
#      become_user: yb
#      become: yes
      

# vim: ts=2 et nowrap autoindent